name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  UV_PYTHON: "3.11"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.31.0

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install UV"
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml

      - name: "Install lint dependencies"
        run: uv sync --only-group lint

      - name: "Python format"
        run: uvx ruff format --diff .

      - name: "Python lint"
        run: uvx ruff check .

      - name: "Python type check"
        run: uv run mypy

  tests:
    name: "Testing with Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml

      - name: "Install dev dependencies"
        run: uv sync --python ${{ matrix.python-version }} --only-dev

      - name: "Run tests"
        run: uv run pytest
        env:
          COVERAGE_FILE: .coverage.py${{ matrix.python-version }}
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: .coverage.py${{ matrix.python-version }}
          path: .coverage.py${{ matrix.python-version }}
          if-no-files-found: error
          include-hidden-files: true


  combine-coverage:
    name: "Combine coverages"
    runs-on: ubuntu-latest
    needs: [ tests ]
    permissions:
      pull-requests: write
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install coverage
        run: pip install coverage[toml]

      - name: Download coverage files
        uses: actions/download-artifact@v4
        with:
          path: coverage
          merge-multiple: true

      - run: coverage combine coverage
      - run: coverage report
      - run: coverage xml

      - name: Store coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage
          include-hidden-files: true

      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./tests-reports/coverage.xml
          threshold: 95
          fail: true
          publish: true
          diff: true
          diff-branch: main
          coverage-summary-title: "Code Coverage Summary"
